### ISSUE TITLE
Apply CRDs first

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#490] opened 2021-01-29 23:46 UTC
Similar to #489 CRDs should be applied first (just like namespaces should go before other resources)

**Comment by sh0rez** [comment] 2021-01-30 18:34
In https://github.com/grafana/tanka/blob/master/pkg/process/sort.go we already sort CRDs before most other meaningful objects – so technically there should not be any order dependencies.

I could imagine that kubectl still disregards this and CRDs need to be applied fully separate – could you check that? 

Using the following is a very good workaround: 
```bash
$ tk apply -t 'CustomResourceDefinition/.+' . # first run, crds only
$ tk apply . # second run, everything
```

I guess we could detect that and automatically apply crds in a separate run. Wdyt?

**Comment by ghostsquad** [comment] 2021-02-02 21:57
ya, your work around is something I will likely implement locally, maybe it should be in the docs? The main problem I think is that `diff` will fail because the kubernetes API won't understand the CRD until CRD is applied. So the client has to apply CRD's first.

**Comment by ghostsquad** [comment] 2021-03-19 22:56
Not stale

**Comment by kubaracek** [comment] 2021-04-21 10:07
I just ran into this. There really should be a mechanism that applies the crds first before doing initial diff.

**Comment by Duologic** [comment] 2021-05-20 21:27
I'd say this is a duplicate of https://github.com/grafana/tanka/issues/246.

**Closed by Duologic** 2021-05-20 21:27 UTC
