### ISSUE TITLE
Supporting Kubernetes objects that use generateName

### ISSUE THREAD

**Issue by wojciechka** [grafana/tanka#526] opened 2021-03-03 10:41 UTC
I have been trying to migrate some of raw jsonnet-based workloads into tanka and one thing I have realized is that some of the workloads use `metadata.generateName` to create a different resource on each deployment.

Specifically we are running Argo Workflows that are deployed at final stage of deployment and run tests to validate the entire system is running properly. Using `generateName` is common in Argo Workflows - such as here: https://argoproj.github.io/argo-workflows/examples/

Kubernetes allows specifying `generateName` to create resources with unique names - https://kubernetes.io/docs/reference/using-api/api-concepts/#generated-values

A minimal example to reproduce this can be done as follows:

1. Run `tk init` in an empty directory
2. Put the following into `environments/default/main.jsonnet` (I'm using a `Job` here, not an Argo Workflow, but the concept is the same)
    ```
    {
      job_with_generatename: {
        apiVersion: 'batch/v1',
        kind: 'Job',
        metadata: {
          generateName: 'myjob-',
        },
        spec: {
          template: {
            spec: {
              containers: [
                {
                  name: 'myjob',
                  image: 'ubuntu:20.04',
                  args: [ 'sleep', '1h' ],
                },
              ],
            },
          },
        },
      },
    }
    ```
3. Run `tk show environments/default` - it will report the following error:
    ```
    Error: .job_with_generatename has missing or invalid fields:
      - metadata.name: Missing or not of string type

    Please check below object:
      apiVersion: batch/v1
      kind: Job
      metadata:
        generateName: myjob-
      spec:
        template:
          spec:
            containers:
      ...
      ```

I have not looked into Tanka code yet, but I am curious as to whether Tanka is not supporting this on purpose or noone has run into this before?

I understand that Tanka is using `metadata.name` to determine things such as filename, but perhaps this could also use `generateName` if it is present - such as taking that value and appending a static string like - `myjob-generateName` or simply `myjob-` in the example above.

Are there any downsides or potential problems with Tanka supporting this? I could not find any issue related to this, so it may be that it's just not implemented today, but could be added.

In my case, I am mostly looking for a way for Tanka to generate the YAML files (i.e. so I can run `tk show` and `tk export`), I am already using other tools to deploy the generated YAML files. I suspect that deploying and comparing objects with `generateName` may be slightly more problematic.

**Comment by Duologic** [comment] 2021-03-03 11:08
I am not familiar with `generateName`, after a quick look at the docs it looks like that is used by Kubernetes to generate the name at runtime, right?

Tanka simply renders the YAMLs so other tools (like ArgoCD) can consume those. The diff/apply workflows will pass along the manifests with `generateName` to `kubectl` and let Kubernetes do its thing. Am I missing something why this would not work with Tanka?

**Comment by wojciechka** [comment] 2021-03-03 11:46
> I am not familiar with `generateName`, after a quick look at the docs it looks like that is used by Kubernetes to generate the name at runtime, right?

That is correct. The generated objects will then have both `generateName` and `name` set. So when doing jsonnet->YAML rendering, there is nothing special that would need to happen.

For example:

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  ...
  generateName: tests-
  labels:
    ...
  name: tests-c664cfc
  ...
```

I don't think that is a problem, but just wanted to share how the object is generated (in this case it was applied using ArgoCD, I am not sure if ArgoCD or Kubernetes was the one who generated the name).

> Tanka simply renders the YAMLs so other tools (like ArgoCD) can consume those. The diff/apply workflows will pass along the manifests with `generateName` to `kubectl` and let Kubernetes do its thing. Am I missing something why this would not work with Tanka?

I am not very familiar with Tanka so I am not sure how `diff` is implemented, but if it is using `kubectl` then hopefully that's all there is to it.

**Comment by Duologic** [comment] 2021-03-03 14:33
By default it uses `kubectl` to diff.

**Comment by wojciechka** [comment] 2021-03-04 10:15
> By default it uses `kubectl` to diff.

That's good to know.

I've managed to make some progress and get `generateName` working with relatively small changes in the codebase:

```
diff --git a/cmd/tk/export.go b/cmd/tk/export.go
index bb55fda..0560074 100644
--- a/cmd/tk/export.go
+++ b/cmd/tk/export.go
@@ -29,7 +29,7 @@ func exportCmd() *cli.Command {

        format := cmd.Flags().String(
                "format",
-               "{{.apiVersion}}.{{.kind}}-{{.metadata.name}}",
+               "{{.apiVersion}}.{{.kind}}-{{or .metadata.name .metadata.generateName}}",
                "https://tanka.dev/exporting#filenames",
        )

diff --git a/pkg/kubernetes/manifest/manifest.go b/pkg/kubernetes/manifest/manifest.go
index 70a36aa..284e86d 100644
--- a/pkg/kubernetes/manifest/manifest.go
+++ b/pkg/kubernetes/manifest/manifest.go
@@ -62,7 +62,7 @@ func (m Manifest) Verify() error {
                if !o.Get("metadata").IsMSI() {
                        fields["metadata"] = ErrInvalidMap
                }
-               if !o.Get("metadata.name").IsStr() {
+               if !o.Get("metadata.name").IsStr() && !o.Get("metadata.generateName").IsStr() {
                        fields["metadata.name"] = ErrInvalidStr
                }
```

The output of `tk show` and `tk export` is what I was expecting it to be.

I suspect it may also require some additional changes, but I'm not that familiar with Tanka codebase yet.

Should I create a PR with the change above? Do you have any other preference for implementing this? Which other files would also need updating?

**Comment by Duologic** [comment] 2021-03-04 10:46
Changing the default export format should not be needed to make this work, feel free to propose something in #528 on that.

Can you provide a minimal reproducible example that shows what you are trying to fix with above code?

**Comment by wojciechka** [comment] 2021-03-04 12:37
> Changing the default export format should not be needed to make this work, feel free to propose something in #528 on that.

This is where I was not sure, which is why I wanted to ask before opening a PR. I'm fine not changing the default value as for my use cases I'll just provide a custom value for `--format` anyway. I just wanted the change to be complete and work in a reasonable way out of the box.

This should not change names of any files in `tk export` because `{{ or ... }}` will use first non-empty value, which is documented in https://golang.org/pkg/text/template/#hdr-Functions.

Without that change, any attempt to generate items with `.metadata.generateName` will cause `<no value>` to be in the filename. For the example I gave in https://github.com/grafana/tanka/issues/526#issue-820983545 and without the default format change the output filename is `batch-v1.Job-<no value>.yaml`. With my format change the name is `batch-v1.Job-myjob-.yaml`.

Again, I'm fine with not changing the default format to avoid any potential or unwanted changed in `tk export`, I don't know Tanka enough to understand potential implications. I simply wanted to make sure my change would behave correctly in defaults and I think it doesn't change behavior for any object that has `.metadata.name` today, which was mandatory anyway, so it should not change anything.

**Comment by Duologic** [comment] 2021-03-04 19:14
That sounds reasonable, looking forward to the PR. Thanks for describing in depth.

**Comment by wojciechka** [comment] 2021-03-05 08:30
> That sounds reasonable, looking forward to the PR. Thanks for describing in depth.

Created #529 

Just realized that's not a `chore`, probably a `feat`, even if the change is small.

**Comment by Duologic** [comment] 2021-03-18 08:13
#529 was merged, release coming soon.

**Closed by Duologic** 2021-03-18 08:13 UTC
