### ISSUE TITLE
relative imports don't work when running `tk` from a top-level directory

### ISSUE THREAD

**Issue by ghostsquad** [grafana/tanka#372] opened 2020-09-03 18:30 UTC
## Description

relative imports don't work if running `tk` from a higher level directory.

```
❯ tk show deploy/environments/test
evaluating jsonnet: RUNTIME ERROR: Field does not exist: environmentName
	main.jsonnet:7:13-38	object <anonymous>
	During manifestation

❯ cd deploy/environments/test

11:27:42 in deploy/environments/test
❯ tk show .
  apiVersion: v1
  kind: deployment
  metadata:
    name: test
    namespace: default
```

## Expected Behavior

Can import files relative to the file mentioning the import

## Actual behavior

error such as:

```
evaluating jsonnet: RUNTIME ERROR: Field does not exist: environmentName
```

## Repro Steps

```
.
├── deploy
│   ├── environments
│   │   └── test
│   │       ├── README.md
│   │       ├── config.libsonnet
│   │       ├── main.jsonnet
│   │       └── spec.json
├── jsonnetfile.json
├── jsonnetfile.lock.json
```

> `main.jsonnet`

```jsonnet
(import './config.libsonnet') +
{
  deployment: {
    apiVersion: "v1",
    kind: "deployment",
    metadata: {
      name: $.config_.environmentName
    },
  },
}
```

> `config.libsonnet`

```
{
  config_+:: {
    environmentName: "test",
  },
}
```

## Extra Data

tanka version `0.11.1`

running

```shell
jsonnet ./deploy/environments/test/main.jsonnet
```

works as expected

**Comment by sh0rez** [comment] 2020-09-03 22:00
Having a hard time reproducing this:


[![asciicast](https://asciinema.org/a/Fvq52BzzY1HKoblkI5JIPxzKI.svg)](https://asciinema.org/a/Fvq52BzzY1HKoblkI5JIPxzKI)

**Comment by ghostsquad** [comment] 2020-09-04 00:29
add one additional step:

add this file to you root directory:

> `config.libsonnet`
```jsonnet
{}
```

**Comment by ghostsquad** [comment] 2020-09-04 00:39
so, it looks like the problem is that `./config.libsonnet` actually refers to multiple files based on the injected JSONNET_PATHs.

I cannot repro this either with jsonnet

```shell
17:37:30 in ~/tmp/test
❯ jsonnet -J $(PWD) deploy/environments/default/main.jsonnet
{
   "deployment": {
      "apiVersion": "v1",
      "kind": "deployment",
      "metadata": {
         "name": "test"
      }
   }
}
```

**Comment by ghostsquad** [comment] 2020-09-04 00:42
based on the above, I think that tanka is not treating relative paths correctly. cc @sbarzowski - can you confirm how jsonnet handles relative paths vs JPATH?

**Comment by sh0rez** [comment] 2020-09-08 08:22
@ghostsquad I am not yet fully through identifying the issue. I can reproduce using v0.11.1, but it seems to have disappeared on master. Could you check?

**Comment by sh0rez** [comment] 2020-09-08 08:27
Alright, it was fixed in https://github.com/grafana/tanka/commit/d60b4a2eb9e980cde87286c0ffe500e8840fe675.

Apparently, the filename passed to `jsonnet.EvaluateSnippet()` has far more meaning than anticipated (assumed it was purely informational for stacktraces)

Turns out, it is what `std.thisFile` returns and apparently also used by the importer.

**Comment by sbarzowski** [comment] 2020-09-08 15:31
FYI there is newer API (EvaluateFile / EvaluateAnonymousSnippet) which should help avoid this sort of trouble in the future. We now distinguish between diagnostic file name (which might include placeholders like <stdin>) and importer filename. https://github.com/google/go-jsonnet/pull/447

**Comment by sh0rez** [comment] 2020-09-14 07:30
Fixed in https://github.com/grafana/tanka/commit/d60b4a2eb9e980cde87286c0ffe500e8840fe675, new API implemented in https://github.com/grafana/tanka/commit/e8b3805e198077e6d1856f40fb25c64c30b7a690

**Closed by sh0rez** 2020-09-14 07:30 UTC
Labels: kind/bug
