### ISSUE TITLE
Remove magic import 'tk'

### ISSUE THREAD

**Issue by Duologic** [grafana/tanka#309] opened 2020-07-01 08:33 UTC
Internally we got bitten by it while trying to resolve TransistiveImports (through symlinks). I'm convinced this is not a good practice. AFAIK this can easily be replaced by `import 'spec.json'` and passed along to libraries in main.jsonnet.

**Comment by sh0rez** [comment] 2020-07-01 11:09
The rationale behind `import "tk"` (or similar) goes beyond the environment itself.

It's supposed to provide access to a variety of data and especially functions Tanka extends Jsonnet with.

For example, then env is actually available as `std.extVar("tanka.dev/environment")`. If we perhaps add secrets to Tanka, we could imagine having native functions like `std.native("tanka.dev/getVault")`. These however are implementation details and as such not suited for user code.

Having a "Tanka standard library" is an answer to this, as provides a documented contract to the user, regardless of how the Jsonnet <-> Go bridge is set up.

Providing a .libsonnet from memory is what we currently use to address this. We could also distribute this libsonnet using jb, which I wouldn't prefer however as it adds another step.

Another option might be to figure out how exactly `std` is bound and do the same.

For mentioned issue, directly importing `spec.json` is fair enough, but I feel like the root cause is that `tk tool imports` should swallow the import, as it doesn't belong outside the scope of Tanka and will never change anyways

**Comment by sh0rez** [comment] 2020-07-01 17:36
As explained at length above, such would be an implementation detail that might change. The Jsonnet wrapper around this provides a stable interface, while allowing us to modify the implementation at will :)

**Comment by Duologic** [comment] 2020-07-01 18:41
How would it be more stable? Do you mean the string would change? What about 'tk', that might change too? The stability is only marginally better.

**Comment by sh0rez** [comment] 2020-07-03 20:32
To me it appears significantly better, given that it adds abstraction over our implementation, allowing us for more flexible refactors.

Consider a scenario where we want to give users the ability to dynamically load secrets from outside. It would be reasonable to let them define a Vault connection in `spec.json`, then offer `tk.sec.<yourSecret>` to access those. 

We might choose a nativeFunc to implement this, but maybe later on switch to something better yet to be introduced to Jsonnet. At this point users would need to adapt their code. 

With the statically provided Jsonnet file however, we could avoid such cases by designing clever function contracts where we can swap the underlying implementation afterwards without a signature change.

Also such a function library could leverage upcoming Jsonnet documentation and analysis frameworks like https://github.com/sh0rez/docsonnet, which could offer a superior experience to reading our online docs searching for extVars and nativeFuncs.

**Comment by sh0rez** [comment] 2021-01-08 11:09
Closing this issue as it is old it does not seem to need an urgent action.

For future reference, there is now https://github.com/grafana/jsonnet-libs/tree/master/tanka-util, and it might make sense to unify the bundled library with that.

In case anybody is interested, please open a new ticket for discussion.

**Closed by sh0rez** 2021-01-08 11:09 UTC
Labels: component/jsonnet, keepalive, lifecycle/discuss
