### ISSUE TITLE
Integrate `jsonnet-lint` as `tk lint`

### ISSUE THREAD

**Issue by josephglanville** [grafana/tanka#571] opened 2021-06-12 22:58 UTC
After `jsonnetfmt` was implemented in Go it was integrated into Tanka with the `tk fmt` subcommand.

It would be great if the same could be done for `jsonnet-lint` as it's also Go and would save on needing to export the Jsonnet path and run the tool manually.

Doing so will make linting more accessible and feel like a more integrated experience.

**Comment by Duologic** [comment] 2021-06-13 07:28
Duplicate of https://github.com/grafana/tanka/issues/342

**Closed by Duologic** 2021-06-13 07:28 UTC
