### ISSUE TITLE
running 'tk env set ...' sets injectLabels to false and removes it from spec.json

### ISSUE THREAD

**Issue by nvtkaszpir** [grafana/tanka#658] opened 2021-12-23 08:09 UTC
**Steps to reproduce:**
we have environments/kind config for KinD setup for tests and we install things in ``monitoring`` namespace.
specj.json:
```json
{
  "apiVersion": "tanka.dev/v1alpha1",
  "kind": "Environment",
  "metadata": {
    "name": "environments/kind",
    "namespace": "environments/kind/main.jsonnet"
  },
  "spec": {
    "apiServer": "https://127.0.0.1:7443",
    "namespace": "monitoring",
    "injectLabels": true,
    "diffStrategy": "native",
    "resourceDefaults": {},
    "expectVersions": {}
  }
}
```
config.libsonnet and main.jsonnet are just basics, nothing fancy, so I'm not adding it here.

Running below command:
```shell
tk env set environments/kind --namespace monitoring
```

**What happens:**
Running above command removes the injectLabels from spec file, the tanka output is:
```text
updated spec.injectLabels (`true` -> `false`)
```

**Expected behaviour:**
injectLabels setting would be preserved in the config

Looks like `` --inject-labels`` is required when performing ``tk env set``, otherwise it is forcefully removed from the config.

**Other info**
tk --version:
```text
tk version v0.19.0
```
binary linux-amd64 - Ubuntu 20.04

**Comment by davidovich** [comment] 2021-12-23 13:23
I believe this is a duplicate of #561. A workaround would be to specify the --inject-labels=true on the command-line.

**Comment by nvtkaszpir** [comment] 2021-12-23 14:11
yeah, looks like a duplicate of #561

**Closed** 2021-12-23 14:11 UTC
