### ISSUE TITLE
Overriding of a library seems to work only for those imported in the environment/default/main.jsonnet

### ISSUE THREAD

**Issue by primeroz** [grafana/tanka#278] opened 2020-05-19 09:11 UTC
My understanding , when reading https://tanka.dev/libraries/overriding, is that any `import` in any jsonnet file , including those nested in the vendor libraries, should follow the import path and override rules described in the docs

In my testing though the override only seem to work for `import` performed in the `main.jsonnet` of the tanka environment

Of course if my understanding is wrong please just close this issue 

Example that follow is for cortex 

**Base Cortex / Tanka setup**
```
➜  tanka-example  tk init
GET https://github.com/ksonnet/ksonnet-lib/archive/0d2f82676817bbf9e4acf6495b2090205f323b9f.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/811ccb022bc2bdcd0b8281ed0a0c858c63e20542.tar.gz 200
Directory structure set up! Remember to configure the API endpoint:
`tk env set environments/default --server=127.0.0.1:6443`
➜  tanka-example  jb install github.com/grafana/cortex-jsonnet/cortex
GET https://github.com/grafana/cortex-jsonnet/archive/da1e8e75fc697a5cf05a7facbb913436fe9e2393.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/811ccb022bc2bdcd0b8281ed0a0c858c63e20542.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/811ccb022bc2bdcd0b8281ed0a0c858c63e20542.tar.gz 200
GET https://github.com/grafana/jsonnet-libs/archive/811ccb022bc2bdcd0b8281ed0a0c858c63e20542.tar.gz 200
```

**main.jsonnet**
```
$ cat environments/default/main.jsonnet 
local cortex = import 'cortex/cortex.libsonnet';

cortex {
  local vars = {
    random_id: 'abcdef',
    project_id: 'project',
    bigtable_name: std.format('cortex-%s', vars.random_id),
    bucket_name: std.format('cortex-%s', vars.random_id),
    cortex_sa_name: std.format('cortex-%s@%s.iam.gserviceaccount.com', [vars.random_id, vars.project_id]),
  },

  cortex_serviceAccount: serviceAccount.new('cortex') +
                         serviceAccount.mixin.metadata.withAnnotationsMixin({ 'iam.gke.io/gcp-service-account': vars.cortex_sa_name }),

  ingester_deployment+:
    $.apps.v1.deployment.mixin.spec.template.spec.withServiceAccountName('cortex'),

  querier_deployment+:
    $.apps.v1.deployment.mixin.spec.template.spec.withServiceAccountName('cortex'),

  table_manager_deployment+:
    $.apps.v1.deployment.mixin.spec.template.spec.withServiceAccountName('cortex'),

  _config+:: {
    namespace: 'cortex',

    schema: [{
      from: '2020-05-15',
      store: 'bigtable-hashed',
      object_store: 'gcs',
      schema: 'v11',
      index: {
        prefix: 'cortex_index_',
        period: '168h',
      },
      chunks: {
        prefix: 'cortex_chunks_',
        period: '168h',
      },
    }],

    storage_backend: 'gcp',
    bigtable_instance: vars.bigtable_name,
    bigtable_project: vars.project_id,
    gcs_bucket_name: vars.bucket_name,

    memcached_replicas: 1,

    querier+: {
      replicas: 3,
    },

  },
}
```

**With no override, we get 3 memcached replicas ( for example )**
```
$ tk show environments/default --dangerous-allow-redirect -t statefulset/memcached | yq read - 'spec.replicas'
3
```

**Try to override just memached.libsonnet**\
which is imported by `cortex.libsonnet` and so not directly imported by `enviroment/default/main.jsonnet`. For simplicity i will just edit the `memcached.libsonnet` and replace the replica count 
```
$ mkdir -p lib/cortex && cp vendor/cortex/memcached.libsonnet lib/cortex
$ vim lib/cortex/memcached.libsonnet
$ diff -u vendor/cortex/memcached.libsonnet lib/cortex/memcached.libsonnet 
--- vendor/cortex/memcached.libsonnet   2020-05-19 10:45:48.104269344 +0200
+++ lib/cortex/memcached.libsonnet      2020-05-19 11:03:05.983929621 +0200
@@ -9,7 +9,7 @@
     local statefulSet = $.apps.v1beta1.statefulSet,
 
     statefulSet:
-      statefulSet.new(self.name, 3, [
+      statefulSet.new(self.name, 1, [
         self.memcached_container,
         self.memcached_exporter,
       ], []) +
```

**Rendering with this override does not work** , still 3 replicas
```
$ tk show environments/default --dangerous-allow-redirect -t statefulset/memcached | yq read - 'spec.replicas'
3
```

**Override cortex.libsonnet**\
to include the local memcached.libsonnet on top of the rest
```
$ cat lib/cortex/cortex.libsonnet 
(import '../../vendor/cortex/cortex.libsonnet') +
(import 'memcached.libsonnet')
```

**Override worked, only one replica for memcached**
```
$ tk show environments/default --dangerous-allow-redirect -t statefulset/memcached | yq read - 'spec.replicas'
1
```

**Comment by sh0rez** [comment] 2020-05-30 08:34
Hi! While imports overriding actually does work without for other files than `main.jsonnet`, the official `jsonnet.FileImporter` implementation (which Tanka also uses) considers local files first, before even looking at the `JPATH`:

```go
// https://github.com/google/go-jsonnet/blob/d1c1457520c7f81554a973185944a84d0584f8c2/imports.go#L223-L242
func (importer *FileImporter) Import(importedFrom, importedPath string) (contents Contents, foundAt string, err error) {
	dir, _ := path.Split(importedFrom)

        // Here it looks at local files first
	found, content, foundHere, err := importer.tryPath(dir, importedPath)
	if err != nil {
		return Contents{}, "", err
	}

        // Only if that failed at the JPATH
	for i := len(importer.JPaths) - 1; !found && i >= 0; i-- {
		found, content, foundHere, err = importer.tryPath(importer.JPaths[i], importedPath)
		if err != nil {
			return Contents{}, "", err
		}
	}
```

Because `vendor/cortex/cortex.libsonnet` does an import of `memcached.libsonnet`, which is satisified by the local file `vendor/cortex/memcached.libsonnet`, the `FileImporter` takes that without checking whether you put a shadowing file into a more specific `JPATH`.

I just discovered this and did not assume such a behavior when writing both the Tanka code and our docs, so both are incorrect.

In this case this is very counter-intuitive, however it is probably a well-chosen property for other use-cases.

@sbarzowski Can you clarify on this?

**Comment by sbarzowski** [comment] 2020-05-30 13:09
First of all, importing was not meant as a mechanism for injecting custom logic / values. For that there are functions, object overriding and extVars. With imports you should know what you're importing and downstream code should not mess with the imports.

In particular if the `cortex` repo has a local import from the same directory, it's a feature and not a bug that it will always be that file, no matter what. Otherwise you could get really surprising behavior with users who accidentally override libraries, just because they're named the same.

There is one use case for intentional overriding that really makes sense and it's mentioned in Tanka docs. Sometimes you may want to fix a dependency without waiting for upstream. The safest way to do it is to fork the whole package and to never just override a single file. This should work with JPATH, because imports going across packages should use JPATH-rooted files.

So in the @primeroz case it seems possible to switch the `memcached/` package or `cortex/` package, but you can't override local use of `cortex/memcached.libsonnet` inside `cortex`. I think this behavior is reasonable.

**Comment by primeroz** [comment] 2020-06-01 07:37
@sbarzowski i understnad, it make sense.

I was a bit confused by the docs and i interpreted it as i was able to just override a single file, but maybe is just me. 
So if you reckon the docs are clear enough then feel free to close this case.

Thanks for the explanation

**Comment by sh0rez** [comment] 2020-06-01 08:58
The docs are indeed not clear, they were written under the impression that your exact approach works. I'll update them and close this

**Comment by sh0rez** [comment] 2021-01-08 11:29
Documentation has been adapted. Closing this issue

**Closed by sh0rez** 2021-01-08 11:29 UTC
Labels: component/jsonnet, keepalive, kind/bug
